name: CI Pipeline for Maven App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manually triggering the workflow
    inputs:
      build_type:
        description: 'Specify the build type (e.g., Debug or Release)'
        default: 'Release'
        required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Maven dependencies and build
      run: mvn clean package -DskipTests=false

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Maven Build Artifact
        path: target/ # Uploads all files in the `target` directory

  sonarcloud-scan:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Configure Maven to Use Sonar 3.x Plugin
      run: |
        mvn org.apache.maven.plugins:maven-settings-plugin:3.1.0:set -Dsonar-maven-plugin.version=3.9.0.2155

    - name: Run SonarCloud Scan
      run: |
        mvn clean verify sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  download-artifact:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: Maven Build Artifact
        path: ./artifact # Downloads the artifact to a local directory

    - name: List Downloaded Files
      run: ls -l ./artifact
